export const ENV_KEYS = {
  DATABASE_URL: 'DATABASE_URL',
  NEWS_API_KEY: 'NEWS_API_KEY',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION: 'AWS_REGION',
  BEDROCK_MODEL_ID: 'BEDROCK_MODEL_ID',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_URL: 'REDIS_URL',
} as const;
